### ISSUE TITLE
Замачания по коду

### ISSUE THREAD

**Issue by gagarski** [Ktlo/PlanetarySystemSimulator#2]
В принципе, при чтении кода глаз почти ни за что коробящее не зацепляется, код довольно чистый и возможности Котлина используются грамотно.

Есть только небольшое сомнение в том, нужен ли класс `Calculator`. Можно добавить эти свойства прямо в `AstronomicalObject`, можно следать их в виде extension-значений.

**Comment by Ktlo** [comment]
Класс Calculator удалён.
