### ISSUE TITLE
Общие улучшения

### ISSUE THREAD

**Issue by gagarski** [Ktlo/PlanetarySystemSimulator#4]
Эти замечания с наиболее низким приоритетом и, в принципе, можно их оставить за пределами работы в этом семестре.
1. В UI определённо не хватает зума и прокрутки. Я начал создавать солнечную систему с реальными параметрами, но моё начинание закончилось, когда я попытался задать массу Солнца в земных массах.
2. (это точно с самым низким приоритетом) Было бы круто сделать возможность экспортировать планетную систему в произвольный файл. Для этого потребуется переработать формат сохранений (например, архив с JSON-описанием и картинками)

**Comment by Ktlo** [comment]
1. Какое-то подобие зума было добавлена.
2. Теперь планетарные системы можно экспортировать и импортировать.
